---
title: "EDA"
output: github_document
---

```{r setup}
library(tidyverse)
library(ggridges)
```

## Load the weather data

```{r}
weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())

head(weather_df)
```

## `group_by`

```{r}
weather_df %>% 
  group_by(name, month) 
```

## Counting things

count months/names observations.
```{r}
weather_df %>% 
  group_by(month) %>% 
  summarise(n_obs = n())

weather_df %>% 
  group_by(name) %>% 
  summarise(n_obs = n())

weather_df %>% 
  group_by(name, month) %>% 
  summarise(n_obs = n())
```
we can use `count()`

```{r}
weather_df %>% 
  count(name, month, name = "n_obs")
```
**NEVER** use base R's 'table'.
1. output is not a data frame.
2.take one variable and make them into table is a bad idea.
```{r, eval=FALSE}
weather_df %>% 
  pull(month) %>% 
  table()
```
other helpful counters.

```{r}
weather_df %>% 
  group_by(month) %>% 
  summarise(
    n_obs = n(), 
    n_days = n_distinct(date))
```

